// Optional browser acceptance checks; requires Playwright + Chromium, not production dependencies.
import assert from 'node:assert/strict';
import { mkdir, mkdtemp, writeFile, readFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { homedir } from 'node:os';
import { pathToFileURL } from 'node:url';
import { startMock } from '../src/mock.ts';
import { startServer } from '../src/server.ts';
import { launch } from '../src/launcher.ts';

let playwright;
try { playwright = await import('playwright'); }
catch {
  const module = process.env.LOWRITER_PLAYWRIGHT_MODULE || join(homedir(), '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
  playwright = await import(pathToFileURL(module).href);
}
await mkdir('.test-data', { recursive: true }); await mkdir('artifacts', { recursive: true });
const dir = await mkdtemp(resolve('.test-data/gui-')), project = join(dir, 'Project with spaces');
await mkdir(project); await writeFile(join(project, 'greeting.js'), 'export const greeting = "Before browser test";\n');
const mock = await startMock();
let app, browser;
const checks = [], errors = [];
try {
  app = await startServer({ dataDir: join(dir, 'private'), port: 0, demo: { endpoint: mock.endpoint, model: 'lowriter-demo', dialect: 'chat-completions', route: 'direct' } });
  browser = await playwright.chromium.launch({ headless: true, channel: process.env.LOWRITER_BROWSER_CHANNEL || (process.platform === 'win32' ? 'msedge' : undefined) });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, colorScheme: 'light', reducedMotion: 'reduce' });
  const page = await context.newPage(); page.on('pageerror', error => errors.push(error.message));
  const launched = await launch({ dataDir: join(dir, 'private'), open: async url => {
    assert.equal(url, app.origin + '/launch'); await page.goto(url);
  } });
  await page.getByRole('heading', { name: 'Every world starts with a few words.' }).waitFor();
  assert.equal(await page.getByLabel('Local pairing code').count(), 0);
  assert.equal(page.url(), app.origin + '/');
  const session = (await context.cookies()).find(cookie => cookie.name === 'lowriter_' + new URL(app.origin).port);
  assert.ok(session?.httpOnly); assert.equal(session?.sameSite, 'Strict');
  checks.push('Automatic launcher sign-in: no code entry, no secret URL, HttpOnly session cookie');
  const second = await context.newPage();
  const reopened = await launch({ dataDir: join(dir, 'private'), open: async url => { await second.goto(url); } });
  await second.getByRole('button', { name: 'New story', exact: false }).waitFor();
  assert.equal(launched.pid, reopened.pid); await second.close();
  checks.push('Repeat launch reuses the same coordinator and opens directly into the workspace');
  const manualContext = await browser.newContext(), manual = await manualContext.newPage();
  await manual.goto(app.origin); await manual.getByText('Advanced: manual browser pairing').click();
  assert.equal(await manual.getByLabel('Local pairing code').getAttribute('type'), 'password');
  await manual.getByLabel('Local pairing code').fill(app.token);
  await manual.getByRole('button', { name: 'Open my workspace' }).click();
  await manual.getByRole('button', { name: 'New story', exact: false }).waitFor(); await manualContext.close();
  checks.push('Advanced manual fallback remains available, masked and separate from normal launch');
  await page.screenshot({ path: 'artifacts/desktop-light.png' });
  await page.getByRole('button', { name: 'Set the scene' }).click();
  const composer = page.getByLabel('Message your writing partner');
  const initialPrompt = await composer.inputValue();
  await composer.press('Control+End');
  await composer.press('Shift+Enter');
  assert.equal(await composer.inputValue(), initialPrompt + '\n');
  let keyboardSends = 0;
  page.on('request', request => { if (request.method() === 'POST' && /\/send$/.test(new URL(request.url()).pathname)) keyboardSends++; });
  await composer.dispatchEvent('keydown', { key: 'Enter', isComposing: true });
  await composer.dispatchEvent('keydown', { key: 'Enter', keyCode: 229 });
  await composer.dispatchEvent('keydown', { key: 'Enter', repeat: true });
  await page.waitForTimeout(150);
  assert.equal(keyboardSends, 0);
  assert.equal(await composer.inputValue(), initialPrompt + '\n');
  await composer.press('Enter');
  await page.locator('.message.assistant:not(.candidate)').waitFor();
  assert.match(await page.locator('.message.assistant:not(.candidate)').innerText(), /last train/);
  const story = app.store.conversations().find(c => c.mode === 'rp');
  assert.equal(app.store.messages(story.id).length, 2);
  assert.equal(keyboardSends, 1);
  await composer.fill('   '); await composer.press('Enter');
  await page.waitForTimeout(150); assert.equal(keyboardSends, 1);
  await composer.fill('');
  checks.push('Enter sends once; Shift+Enter inserts a newline; IME confirmation, repeated keys and empty drafts do not send');
  checks.push('Writing UI sends, displays and persists a completed mock reply');
  const assistantMessage = page.locator('.message.assistant:not(.candidate)');
  const markdown = '# Heading one\n\n### Heading three\n\n**Bold** and *italic* and ~~strike~~ &amp; text.\n\n- First item\n- Second item\n\n> Quoted text\n\n`literal *stars*`\n\n```js\nconst value = "**keep**";\n```\n\n| Name | Value |\n| --- | --- |\n| A | B |\n\n[safe link](https://example.com) [blocked link](javascript:alert(1))\n\n![No background request](https://synthetic.invalid/track.png)\n\n<script>window.markdownUnsafe = true</script>\n<img src="https://synthetic.invalid/raw.png" onerror="window.markdownUnsafe=true">';
  const requestsBeforeEdit = keyboardSends;
  let externalImages = 0; page.on('request', r => { if (r.url().includes('synthetic.invalid')) externalImages++; });
  await assistantMessage.getByRole('button', { name: 'Edit message', exact: true }).click();
  await page.getByLabel('Edit message text', { exact: true }).fill(markdown);
  await page.getByRole('button', { name: 'Save message', exact: true }).click();
  await assistantMessage.locator('.formatted-message strong').waitFor();
  assert.equal(await assistantMessage.locator('.formatted-message strong').innerText(), 'Bold');
  assert.equal(await assistantMessage.locator('.formatted-message em').innerText(), 'italic');
  assert.equal(await assistantMessage.locator('.formatted-message h2').count(), 1);
  assert.equal(await assistantMessage.locator('.formatted-message h3').count(), 1);
  assert.equal(await assistantMessage.locator('.formatted-message li').count(), 2);
  assert.equal(await assistantMessage.locator('blockquote').innerText(), 'Quoted text');
  assert.equal(await assistantMessage.locator('pre code').innerText(), 'const value = "**keep**";');
  assert.equal(await assistantMessage.locator('table td').count(), 2);
  assert.equal(await assistantMessage.locator('.formatted-message a').count(), 1);
  assert.equal(await assistantMessage.locator('img,script,iframe').count(), 0);
  assert.equal(await page.evaluate(() => window.markdownUnsafe), undefined);
  assert.equal(externalImages, 0); assert.equal(keyboardSends, requestsBeforeEdit);
  assert.equal(app.store.messages(story.id)[1].content, markdown);
  await page.screenshot({ path: 'artifacts/message-formatting-desktop.png' });
  await assistantMessage.getByRole('button', { name: 'Show raw text', exact: true }).click();
  assert.equal(await assistantMessage.locator('.raw-message').textContent(), markdown);
  await assistantMessage.getByRole('button', { name: 'Show formatting', exact: true }).click();
  await assistantMessage.getByRole('button', { name: 'Edit message', exact: true }).click();
  const editor = page.getByLabel('Edit message text', { exact: true });
  await editor.fill('Selected words');
  await editor.evaluate(el => { el.focus(); el.select(); });
  await page.getByRole('button', { name: 'Bold', exact: true }).click();
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(resolve)));
  assert.equal(await editor.inputValue(), '**Selected words**');
  await editor.fill('First line\nSecond line');
  await editor.evaluate(el => { el.focus(); el.select(); });
  await page.getByRole('button', { name: 'List', exact: true }).click();
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(resolve)));
  assert.equal(await editor.inputValue(), '- First line\n- Second line');
  await editor.fill('Heading from cursor');
  await editor.evaluate(el => el.setSelectionRange(8, 8));
  await page.getByRole('button', { name: 'Heading 2', exact: true }).click();
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(resolve)));
  assert.equal(await editor.inputValue(), '## Heading from cursor');
  await editor.press('End'); await editor.press('Enter');
  assert.equal(keyboardSends, requestsBeforeEdit);
  await page.screenshot({ path: 'artifacts/message-editor-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await editor.scrollIntoViewIfNeeded();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: 'artifacts/message-editor-mobile.png' });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await editor.fill('Cancelled change');
  await assistantMessage.getByRole('button', { name: 'Cancel edit', exact: true }).click();
  assert.equal(app.store.messages(story.id)[1].content, markdown);
  checks.push('Markdown defaults to formatted bold/italic/headings/lists/quotes/code/tables with exact raw toggle; no executable HTML, unsafe links or automatic image requests');
  checks.push('Saved message Edit/Save/Cancel preserves original Markdown, changes no later replies and starts no provider request');
  checks.push('Formatting toolbar wraps selected text, prefixes selected lines and inserts headings at line boundaries; editor Enter never sends and mobile editor fits');
  await page.getByRole('button', { name: 'Appearance', exact: false }).click();
  assert.equal(await page.getByLabel('Color theme', { exact: true }).count(), 0);
  assert.ok(await page.getByLabel('Text size', { exact: false }).isVisible());
  const fontSlider = page.getByLabel('Text size', { exact: false }), widthSlider = page.getByLabel('Reading width', { exact: false });
  await fontSlider.fill('22'); await widthSlider.fill('900');
  await page.getByLabel('Message font', { exact: true }).selectOption('sans');
  await page.getByLabel('Line spacing', { exact: false }).fill('2.2');
  await page.getByLabel('Paragraph spacing', { exact: false }).fill('1.5');
  await page.getByLabel('Letter spacing', { exact: false }).fill('0.5');
  await page.getByLabel('Your dialogue color', { exact: true }).fill('#bb6611');
  await page.getByLabel('Appearance preset name', { exact: true }).fill('Fixture reading');
  await page.getByRole('button', { name: 'Save appearance preset', exact: true }).click();
  await page.getByRole('button', { name: 'Reset text size', exact: true }).click();
  assert.equal(await fontSlider.inputValue(), '17'); assert.equal(await widthSlider.inputValue(), '900');
  await page.getByRole('button', { name: 'Reset appearance to defaults', exact: true }).click();
  assert.equal(await widthSlider.inputValue(), '760');
  await page.getByLabel('Appearance presets', { exact: true }).selectOption('Fixture reading');
  assert.equal(await fontSlider.inputValue(), '22'); assert.equal(await widthSlider.inputValue(), '900');
  assert.equal(await page.getByLabel('Message font', { exact: true }).inputValue(), 'sans');
  assert.equal(await page.getByLabel('Line spacing', { exact: false }).inputValue(), '2.2');
  assert.equal(await page.getByLabel('Paragraph spacing', { exact: false }).inputValue(), '1.5');
  assert.equal(await page.getByLabel('Letter spacing', { exact: false }).inputValue(), '0.5');
  const typography = await page.locator('.appearance-sample').evaluate(el => { const s = getComputedStyle(el); return { font: s.fontFamily, lineHeight: parseFloat(s.lineHeight), size: parseFloat(s.fontSize), spacing: s.letterSpacing }; });
  assert.match(typography.font, /sans-serif/); assert.ok(Math.abs(typography.lineHeight / typography.size - 2.2) < 0.01); assert.equal(typography.spacing, '0.5px');
  await page.getByLabel('Letter spacing', { exact: false }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'artifacts/appearance-typography.png' });
  await page.getByRole('button', { name: 'Reset appearance to defaults', exact: true }).click();
  checks.push('Named appearance preset saves/loads; per-field and Appearance resets leave saved presets intact');
  await page.getByRole('button', { name: 'Close settings' }).click();
  await page.getByRole('button', { name: 'Dark mode', exact: true }).click();
  assert.equal(await page.getByRole('dialog').count(), 0);
  assert.equal(await page.getByRole('button', { name: 'Dark mode', exact: true }).getAttribute('aria-pressed'), 'true');
  await page.screenshot({ path: 'artifacts/desktop-dark.png' });
  await page.reload();
  await page.getByRole('button', { name: 'New story', exact: false }).waitFor();
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
  await page.getByRole('button', { name: 'Appearance', exact: false }).click();
  await page.getByLabel('Appearance presets', { exact: true }).selectOption('Fixture reading');
  assert.equal(await page.getByLabel('Text size', { exact: false }).inputValue(), '22');
  assert.equal(await page.getByLabel('Message font', { exact: true }).inputValue(), 'sans');
  assert.equal(await page.getByLabel('Line spacing', { exact: false }).inputValue(), '2.2');
  assert.equal(await page.getByLabel('Letter spacing', { exact: false }).inputValue(), '0.5');
  await page.getByRole('button', { name: 'Reset line spacing', exact: true }).click();
  assert.equal(await page.getByLabel('Line spacing', { exact: false }).inputValue(), '1.9');
  await page.getByRole('button', { name: 'Reset appearance to defaults', exact: true }).click();
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
  await page.getByRole('button', { name: 'Close settings' }).click();
  await page.locator('.conversation-link').first().click();
  await page.locator('.message.assistant:not(.candidate)').waitFor();
  checks.push('Theme and history survive browser reload');
  checks.push('Precise font, line/paragraph/letter spacing controls save in presets, survive reload and reset independently');
  await page.getByRole('button', { name: 'Follow system theme', exact: true }).click();
  await page.emulateMedia({ colorScheme: 'light' });
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'light');
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'dark');
  await page.getByRole('button', { name: 'Light mode', exact: true }).focus();
  await page.keyboard.press('Enter');
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'light');
  await page.getByRole('button', { name: 'Dark mode', exact: true }).click();
  checks.push('Compact header color-mode controls work without Appearance; keyboard activation and live system-theme changes passed');
  await page.getByLabel('Message your writing partner').fill('[slow]');
  await page.getByRole('button', { name: 'Send', exact: false }).click();
  await page.getByRole('button', { name: 'Stop reply', exact: false }).click();
  await page.getByText('cancelled · uncommitted candidate').waitFor();
  assert.equal(app.store.messages(story.id).length, 3);
  checks.push('GUI cancellation leaves candidate uncommitted');
  await page.getByRole('button', { name: 'Assistant', exact: true }).click();
  await page.getByText('Ask questions, explore ideas, draft something, or work on code.', { exact: false }).waitFor();
  await page.screenshot({ path: 'artifacts/assistant-welcome.png' });
  await page.getByLabel('Ask a question or describe a task').fill('Explain why the sky is blue.');
  await page.getByLabel('Ask a question or describe a task').press('Enter');
  await page.locator('.message.assistant:not(.candidate)').waitFor();
  const everyday = app.store.conversations().find(c => c.mode === 'coding');
  assert.equal(everyday.title, 'Explain why the sky is blue.'); assert.equal(everyday.trusted, 0); assert.ok(!everyday.project);
  assert.equal(app.store.latestJob(everyday.id).actions.length, 0);
  assert.equal(await page.getByRole('button', { name: 'Story setup', exact: true }).count(), 0);
  checks.push('Assistant sends an everyday question with Enter without selecting a project; no story controls or file actions');
  await page.getByRole('button', { name: 'New chat', exact: false }).click();
  await page.getByRole('button', { name: 'Choose project', exact: true }).click();
  await page.getByLabel('Absolute folder path').fill(project);
  await page.getByRole('button', { name: 'Select without trust' }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  const coding = app.store.conversations().find(c => c.mode === 'coding');
  assert.equal(app.store.conversation(coding.id).trusted, 0);
  await page.getByRole('button', { name: 'Choose project', exact: true }).click();
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Grant project trust' }).click();
  await page.getByRole('button', { name: 'Project trusted', exact: false }).waitFor();
  await page.getByRole('button', { name: 'Try the coding demo', exact: false }).click();
  await page.getByRole('button', { name: 'Send', exact: false }).click();
  await page.locator('.message.assistant:not(.candidate)').waitFor();
  assert.match(await readFile(join(project, 'greeting.js'), 'utf8'), /Hello from LoWriter/);
  assert.equal(app.store.latestJob(coding.id).actions.length, 4);
  assert.match(await page.locator('.action-panel').innerText(), /Hello from LoWriter/);
  await page.screenshot({ path: 'artifacts/coding-desktop.png' });
  checks.push('Folder selection is separate from trust; four real file actions and diff shown');
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Restore this edit' }).click();
  await page.getByRole('status').filter({ hasText: 'Checkpoint restored' }).waitFor();
  assert.match(await readFile(join(project, 'greeting.js'), 'utf8'), /Before browser test/);
  checks.push('Visible checkpoint restoration returns original file');
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.getByRole('button', { name: 'Light mode', exact: true }).isVisible());
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.getByRole('button', { name: 'Open navigation' }).click();
  await page.getByRole('button', { name: 'Writing', exact: true }).click();
  await page.getByRole('button', { name: 'Open navigation' }).click();
  await page.getByRole('button', { name: 'New story', exact: false }).click();
  await page.getByRole('heading', { name: 'Every world starts with a few words.' }).waitFor();
  await page.screenshot({ path: 'artifacts/mobile-dark.png' });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  assert.ok(await page.locator('.composer').isVisible());
  await page.getByRole('button', { name: 'Light mode', exact: true }).click();
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'light');
  assert.equal(await page.getByRole('dialog').count(), 0);
  await page.screenshot({ path: 'artifacts/mobile-light.png' });
  checks.push('390px responsive layout, light/dark themes and mobile navigation; no horizontal overflow');
  await page.getByRole('button', { name: 'Open navigation' }).click();
  await page.getByRole('button', { name: 'Connections', exact: false }).click();
  assert.equal(await page.getByLabel('Create a vault passphrase').count(), 0);
  assert.equal(await page.getByLabel('API key', { exact: false }).getAttribute('type'), 'password');
  assert.equal(await page.getByRole('button', { name: 'Save connection', exact: true }).isEnabled(), true);
  assert.ok(app.vault.automatic && app.vault.key);
  // Provider selection and saving use synthetic credentials only; no public provider calls.
  const provider = page.getByLabel('Provider', { exact: true });
  async function assertConnectionFieldOrder() {
    const order = await page.locator('.connection-form fieldset').evaluate(fieldset => {
      const children = [...fieldset.children];
      const name = children.findIndex(e => e.tagName === 'LABEL' && e.textContent.startsWith('Connection name'));
      const base = children.findIndex(e => e.classList.contains('endpoint-preview') || (e.tagName === 'LABEL' && e.textContent.startsWith('API base URL')));
      const key = children.findIndex(e => e.tagName === 'LABEL' && e.textContent.startsWith('API key / proxy password'));
      return { name, base, key };
    });
    assert.ok(order.name >= 0);
    assert.equal(order.base, order.name + 1);
    assert.equal(order.key, order.base + 1);
    assert.equal(await page.getByLabel('API key', { exact: false }).getAttribute('type'), 'password');
  }
  assert.equal(await provider.locator('option').count(), 20);
  const providerIds = await provider.locator('option').evaluateAll(options => options.map(o => o.value));
  for (const id of providerIds.filter(id => id !== 'custom')) {
    await provider.selectOption(id);
    assert.equal(await page.getByLabel('API base URL', { exact: true }).count(), 0);
    assert.match(await page.locator('.endpoint-preview code').innerText(), /^https:\/\//);
    assert.equal(await page.getByLabel('Network route', { exact: true }).inputValue(), 'auto');
    await assertConnectionFieldOrder();
  }
  checks.push('All 19 built-in presets selectable with automatic API bases and automatic network routing');
  for (const category of ['chat-completions', 'responses', 'anthropic', 'gemini', 'speech', 'speech-openai', 'images', 'gemini-images']) {
    await page.getByLabel('API category', { exact: true }).selectOption(category);
    assert.equal(await provider.inputValue(), 'custom');
    await assertConnectionFieldOrder();
    await page.getByLabel('API base URL', { exact: true }).fill('http://synthetic.onion/v1');
    try { await page.getByRole('status').filter({ hasText: 'Automatic route: TOR.' }).waitFor(); }
    catch (error) {
      console.log(JSON.stringify({ category, endpoint: await page.getByLabel('API base URL', { exact: true }).inputValue(), statuses: await page.getByRole('status', { includeHidden: true }).allTextContents(), pageErrors: errors }));
      await page.screenshot({ path: 'artifacts/connection-failure.png' });
      throw error;
    }
    await page.getByLabel('API base URL', { exact: true }).fill('http://synthetic.i2p/v1');
    await page.getByRole('status').filter({ hasText: 'Automatic route: I2P.' }).waitFor();
    await page.getByLabel('API base URL', { exact: true }).fill('https://synthetic.invalid/v1');
    await page.getByRole('status').filter({ hasText: 'Automatic route: regular / direct.' }).waitFor();
  }
  checks.push('Custom endpoints available in all eight categories; live route hint switches regular/onion/I2P');
  checks.push('Connection name, API base and masked key are adjacent and ordered for all built-in providers and custom categories');
  await page.getByLabel('API category', { exact: true }).selectOption('anthropic');
  await page.getByLabel('API base URL', { exact: true }).fill('http://synthetic.onion/v1');
  await page.getByLabel('Proxy authentication', { exact: true }).selectOption('bearer');
  await page.getByLabel('API key', { exact: false }).fill('synthetic-browser-key');
  await page.getByLabel('Exact model ID', { exact: true }).fill('fixture-model');
  await page.getByLabel('Connection name', { exact: false }).fill('My fixture Claude proxy');
  await page.getByRole('button', { name: 'Save connection', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Connection saved and selected.' }).waitFor();
  assert.equal(await page.getByLabel('API key', { exact: false }).inputValue(), '');
  const saved = app.store.setting('connection'); assert.equal(saved.route, 'auto'); assert.equal(saved.auth, 'bearer'); assert.ok(saved.hasKey);
  assert.ok(!JSON.stringify(app.store.setting('connections')).includes('synthetic-browser-key'));
  await page.getByLabel('API category', { exact: true }).selectOption('all');
  await provider.selectOption('gemini'); assert.equal(await page.getByLabel('API key', { exact: false }).inputValue(), '');
  let catalogs = 0;
  await page.route('**/api/models', async route => { catalogs++; await route.fulfill({ json: { models: [{ id: 'fixture-native-model', name: 'Fixture native model' }], source: 'fixture', partial: false, note: 'Synthetic browser catalog; not a provider request.' } }); });
  await page.getByRole('button', { name: 'Load models', exact: true }).click();
  await page.getByLabel('Model picker', { exact: true }).selectOption('fixture-native-model');
  assert.equal(await page.getByLabel('Exact model ID', { exact: true }).inputValue(), 'fixture-native-model'); assert.equal(catalogs, 1);
  await page.unroute('**/api/models');
  await page.getByLabel('Saved connections', { exact: true }).selectOption(saved.profileId);
  assert.equal(await page.getByLabel('API base URL', { exact: true }).inputValue(), 'http://synthetic.onion/v1');
  assert.equal(await page.getByLabel('Proxy authentication', { exact: true }).inputValue(), 'bearer');
  assert.equal(await page.getByLabel('API key', { exact: false }).getAttribute('placeholder'), '********');
  const countBeforeReset = app.store.setting('connections').length;
  await page.getByRole('button', { name: 'Reset this API category to defaults', exact: true }).click();
  assert.equal(await page.getByLabel('API base URL', { exact: true }).inputValue(), '');
  assert.equal(app.store.setting('connections').length, countBeforeReset);
  assert.equal(app.vault.get(saved.credentialId), 'synthetic-browser-key');
  await page.getByLabel('Saved connections', { exact: true }).selectOption(saved.profileId);
  await page.getByLabel('Connection name', { exact: false }).fill('Second fixture model');
  await page.getByLabel('Exact model ID', { exact: true }).fill('fixture-model-two');
  await page.getByRole('button', { name: 'Save connection', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Connection saved and selected.' }).waitFor();
  assert.equal(app.store.setting('connections').length, countBeforeReset + 1);
  await page.getByLabel('Saved connections', { exact: true }).selectOption(saved.profileId);
  assert.equal(await page.getByLabel('Exact model ID', { exact: true }).inputValue(), 'fixture-model');
  await page.getByText('Advanced network settings (optional)', { exact: true }).click();
  await page.getByLabel('Network proxy URL', { exact: true }).fill('socks5h://127.0.0.1:9150');
  await page.getByRole('button', { name: 'Reset network defaults', exact: true }).click();
  assert.equal(await page.getByLabel('Network proxy URL', { exact: true }).inputValue(), '');
  checks.push('Connection/category and network resets preserve saved passwords; distinct named models save independently for the same API endpoint');
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.locator('.modal').evaluate(e => { e.scrollTop = 0; });
  await page.screenshot({ path: 'artifacts/connections-mobile.png' });
  await page.getByLabel('API key', { exact: false }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'artifacts/connection-fields-mobile.png' });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await assertConnectionFieldOrder();
  await page.locator('.modal').evaluate(e => { e.scrollTop = 0; });
  await page.screenshot({ path: 'artifacts/connections-desktop.png' });
  await page.getByLabel('API key', { exact: false }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'artifacts/connection-fields-desktop.png' });
  checks.push('Custom profile saves/restores masked scoped key and auth; explicit fixture model loading; responsive connection form');
  await page.getByLabel('API category', { exact: true }).selectOption('speech');
  await provider.selectOption('elevenlabs');
  await page.getByLabel('Exact model ID', { exact: true }).fill('synthetic-voice-model');
  await page.getByRole('button', { name: 'Save speech connection', exact: true }).click();
  await page.getByRole('status').filter({ hasText: 'Speech connection saved; writing connection unchanged.' }).waitFor();
  assert.equal(app.store.setting('connection').credentialId, saved.credentialId);
  assert.equal(app.store.setting('speechConnection').provider, 'elevenlabs');
  assert.equal(await page.getByRole('button', { name: 'Generate speech (uses credits)', exact: true }).isDisabled(), true);
  checks.push('ElevenLabs speech saved separately without replacing writing connection or generating paid audio');
  await page.getByLabel('Voice ID', { exact: true }).fill('fixture-voice');
  await page.getByLabel('Speech text', { exact: true }).fill('Synthetic, never generated.');
  await page.getByRole('button', { name: 'Reset speech inputs', exact: true }).click();
  assert.equal(await page.getByLabel('Voice ID', { exact: true }).inputValue(), '');
  assert.equal(await page.getByLabel('Speech text', { exact: true }).inputValue(), '');
  assert.equal(await page.getByRole('button', { name: 'Unlock vault', exact: true }).count(), 0);
  checks.push('Automatic saved credentials need no vault password; masking and separate speech reset passed');
  await page.getByRole('button', { name: 'Close settings' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Open navigation' }).click();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Quit LoWriter', exact: false }).click();
  await page.getByRole('heading', { name: 'See you next time.' }).waitFor(); await app.closed;
  checks.push('Quit LoWriter shuts down the service and shows a clear closed-workspace screen');
  assert.deepEqual(errors, []);
  const report = { date: new Date().toISOString(), platform: process.platform, runtime: process.version, browser: await browser.version(), checks, pageErrors: errors, termux: 'Not tested on real device', liveProvider: 'Not tested; mock only' };
  await writeFile('artifacts/ui-report.json', JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
} finally {
  await browser?.close(); await app?.close(); await mock.close();
}
