import { useEffect, useRef, useState } from 'preact/hooks';
import type { Connection, Message, VoiceProfile } from '../src/shared.ts';
import { isImage, isSpeech } from '../src/shared.ts';
import './media.css';

export interface MediaState { imageConnection: Connection | null; speechConnection: Connection | null; voices: VoiceProfile[] }
async function post(path: string, input: unknown) {
  const r = await fetch('/api' + path, { method: 'POST', headers: { 'X-LoWriter': '1', 'Content-Type': 'application/json' }, body: JSON.stringify(input) });
  const value = await r.json(); if (!r.ok) throw new Error(value.error || 'Media request failed.'); return value;
}
function preferredVoice(story: string) { try { return localStorage.getItem('lowriter-voice-' + story) || ''; } catch { return ''; } }
export function VoiceLibrary({ profiles, voices, onSaved, onConnections }: { profiles: Connection[]; voices: VoiceProfile[]; onSaved: () => Promise<unknown>; onConnections: () => void }) {
  const speech = profiles.filter(c => isSpeech(c.dialect));
  const [connection, setConnection] = useState(speech[0]?.profileId || ''), [name, setName] = useState('Narrator'), [voice, setVoice] = useState(''), [speed, setSpeed] = useState(1);
  const [catalog, setCatalog] = useState<{ id: string; name: string }[]>([]), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const selected = speech.find(c => c.profileId === connection);
  async function run(fn: () => Promise<void>) { setBusy(true); setError(''); setNotice(''); try { await fn(); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }
  return <section class="voice-library"><p>Save a voice once, then choose it below any message. Presets stay tied to their own provider/proxy; a voice ID is never silently moved to another endpoint.</p>
    <button onClick={onConnections}>Configure image / speech connections</button>
    <h3>Saved voices</h3>{!voices.length && <p class="hint">No voices yet. Add ElevenLabs or an OpenAI-compatible speech connection, then choose a voice or paste its ID here.</p>}
    <div class="voice-presets">{voices.map(v => <button disabled={busy} key={v.id} onClick={() => { setConnection(v.connection); setName(v.name); setVoice(v.voice); setSpeed(v.speed); setCatalog([]); }}>{v.name}<small>{v.voice} · {v.speed}×</small></button>)}</div>
    <form onSubmit={e => { e.preventDefault(); void run(async () => { await post('/voice-presets', { name, connection, voice, speed }); await onSaved(); setNotice('Voice saved. Choose it on a message to listen; no speech was generated by saving.'); }); }}>
      <fieldset disabled={busy}><label>Speech connection<select aria-label="Speech connection" value={connection} required onChange={e => { setConnection(e.currentTarget.value); setVoice(''); setCatalog([]); }}><option value="">Choose a saved speech connection…</option>{speech.map(c => <option value={c.profileId}>{c.name || c.provider} · {c.model}</option>)}</select></label>
      <button type="button" disabled={!selected} onClick={() => void run(async () => { const r = await post('/voices', { ...selected, keyMode: 'keep' }); setCatalog(r.voices); setNotice(r.source === 'documentation' ? 'Built-in voice suggestions; model availability varies. Custom voice IDs also work where supported.' : r.partial ? 'Partial catalog; you may also paste a voice ID.' : 'Voice catalog loaded.'); })}>Load available voices</button>
      {!!catalog.length && <label>Available voice<select aria-label="Available voice" value={voice} onChange={e => { const v = catalog.find(v => v.id === e.currentTarget.value); if (v) { setVoice(v.id); setName(v.name); } }}><option value="">Choose…</option>{catalog.map(v => <option value={v.id}>{v.name}</option>)}</select></label>}
      <label>Voice preset name<input value={name} maxLength={80} required onInput={e => setName(e.currentTarget.value)}/></label>
      <label>Voice ID / built-in voice name<input value={voice} maxLength={200} required onInput={e => setVoice(e.currentTarget.value)}/></label>
      <label>Voice speed · {speed.toFixed(2)}×<input type="range" min="0.7" max="1.2" step="0.05" value={speed} onInput={e => setSpeed(Number(e.currentTarget.value))}/></label>
      <button type="button" onClick={() => { setName('Narrator'); setVoice(''); setSpeed(1); setCatalog([]); }}>Reset voice draft</button><button class="primary" disabled={!selected || !voice || !name}>Save voice preset</button></fieldset>
    </form><p class="hint">Saving the same name and connection updates that preset. These are existing voice IDs—not cloning or shared-library imports. Generated speech is AI audio. Sound effects, music and character-card assignments are not part of this slice.</p>
    {error && <p role="alert" class="error">{error}</p>}{notice && <p role="status">{notice}</p>}
  </section>;
}

export function MessageMedia({ message, revision, latest, disabled, profiles, mediaState, onChanged, onManage, story = false, assignedVoice }: { message: Message; revision: number; latest: boolean; disabled: boolean; profiles: Connection[]; mediaState: MediaState; onChanged: () => Promise<unknown>; onManage: () => void; story?: boolean; assignedVoice?: string }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [illustrate, setIllustrate] = useState(false);
  const [prompt, setPrompt] = useState(('Illustrate this story scene. Preserve the described characters and setting.\n\n' + message.content).slice(0, 8000));
  const [connection, setConnection] = useState(mediaState.imageConnection?.profileId || profiles.find(c => isImage(c.dialect))?.profileId || '');
  const [size, setSize] = useState('1024x1024'), [useInChat, setUseInChat] = useState(true);
  const [voice, setVoice] = useState(preferredVoice(message.conversation) || mediaState.voices[0]?.id || '');
  useEffect(() => { if (assignedVoice && mediaState.voices.some(v => v.id === assignedVoice)) setVoice(assignedVoice); }, [assignedVoice]);
  useEffect(() => { if (!connection && mediaState.imageConnection?.profileId) setConnection(mediaState.imageConnection.profileId); }, [mediaState.imageConnection?.profileId]);
  useEffect(() => { if (!voice && mediaState.voices[0]) setVoice(mediaState.voices[0].id); }, [mediaState.voices.length]);
  const images = (message.media || []).filter(a => a.kind === 'image'), selected = images.find(a => a.selected), index = images.findIndex(a => a.selected);
  const audio = (message.media || []).filter(a => a.kind === 'audio');
  const [audioId, setAudioId] = useState(audio.at(-1)?.id || ''), [play, setPlay] = useState(0); const audioRef = useRef<HTMLAudioElement>(null);
  useEffect(() => { if (play) void audioRef.current?.play().catch(() => {}); }, [play, audioId]);
  const pointer = useRef<{ x: number; y: number } | null>(null);
  const variants = message.variants || [], variantIndex = variants.findIndex(v => v.id === message.active_variant), locked = busy || disabled;
  const path = `/conversations/${message.conversation}/messages/${message.id}`;
  async function run(action: string, input: Record<string, unknown> = {}) {
    setBusy(true); setError(''); setNotice('');
    try { const r = await post(path + '/' + action, { revision, ...input }); await onChanged(); if (action === 'narrate') { setAudioId(r.asset.id); setPlay(p => p + 1); setNotice(r.cached ? 'Playing saved audio. No provider request.' : 'AI speech saved locally.'); } }
    catch (e: any) { setError(e.message); } finally { setBusy(false); }
  }
  function swipeImage(next: number) { if (!locked && images[next]) void run('select-image', { asset: images[next].id, useInChat: !!selected?.use_in_chat }); }
  return <section class="message-media" aria-label="Message variants and media">
    <div class="message-controls">
      {story && latest && message.role === 'assistant' && <button disabled={locked} onClick={() => void run('continue')}>Continue reply</button>}
      {message.role === 'assistant' && latest && <><button disabled={locked || variantIndex <= 0} aria-label="Previous reply variant" onClick={() => void run('swipe', { variant: variants[variantIndex - 1]?.id })}>‹</button><span>Reply {Math.max(0, variantIndex) + 1} / {Math.max(1, variants.length)}</span><button disabled={locked || variantIndex < 0 || variantIndex >= variants.length - 1} aria-label="Next reply variant" onClick={() => void run('swipe', { variant: variants[variantIndex + 1]?.id })}>›</button><button disabled={locked} onClick={() => void run('regenerate')}>Regenerate reply</button></>}
      <button disabled={locked} aria-expanded={illustrate} onClick={() => setIllustrate(!illustrate)}>Illustrate scene</button>
      <button onClick={onManage}>Voices & media settings</button>
    </div>
    {illustrate && <div class="illustration-form"><p class="hint">Generate one new image variant. Existing variants are kept. The prompt below—not hidden chat history—is sent to the image provider. Regeneration makes a fresh image, not a reference-image edit.</p>
      <label>Image connection<select aria-label="Image connection" value={connection} disabled={locked} onChange={e => setConnection(e.currentTarget.value)}><option value="">Choose a saved image connection…</option>{profiles.filter(c => isImage(c.dialect)).map(c => <option value={c.profileId}>{c.name || c.provider} · {c.model}</option>)}</select></label>
      <label>Image prompt<textarea value={prompt} rows={4} maxLength={8000} disabled={locked} onInput={e => setPrompt(e.currentTarget.value)}/></label>
      <label>Image size<select aria-label="Image size" disabled={locked || profiles.find(c => c.profileId === connection)?.dialect === 'gemini-images'} value={size} onChange={e => setSize(e.currentTarget.value)}><option value="1024x1024">Square</option><option value="1536x1024">Landscape</option><option value="1024x1536">Portrait</option></select><small>Gemini uses its model's default size in this version.</small></label>
      <label class="check-label"><input type="checkbox" checked={useInChat} disabled={locked} onChange={e => setUseInChat(e.currentTarget.checked)}/><span>Use the selected image in future chat requests</span></label>
      <button class="primary" disabled={locked || !connection || !prompt.trim()} onClick={() => void run('generate-image', { connection, prompt, size, useInChat })}>{images.length ? 'Generate another image (uses credits)' : 'Generate image (uses credits)'}</button>
      <button disabled={locked} onClick={() => { setPrompt(('Illustrate this story scene.\n\n' + message.content).slice(0, 8000)); setSize('1024x1024'); setUseInChat(true); }}>Reset image draft</button>
    </div>}
    {selected && <figure class="story-image"><div class="image-swipe" tabIndex={0} role="group" aria-label="Image variants" onKeyDown={e => { if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') { e.preventDefault(); swipeImage(index + (e.key === 'ArrowLeft' ? -1 : 1)); } }} onPointerDown={e => { pointer.current = { x: e.clientX, y: e.clientY }; }} onPointerCancel={() => { pointer.current = null; }} onPointerUp={e => { const start = pointer.current; pointer.current = null; if (start && Math.abs(e.clientX - start.x) > 60 && Math.abs(e.clientY - start.y) < 60) swipeImage(index + (e.clientX < start.x ? 1 : -1)); }}>
      <img src={'/api/media/' + selected.id} alt={'Selected story illustration · ' + selected.label} loading="lazy" draggable={false}/></div>
      <figcaption><button disabled={locked || index <= 0} aria-label="Previous image variant" onClick={() => swipeImage(index - 1)}>‹</button><span>Image {index + 1} / {images.length}</span><button disabled={locked || index >= images.length - 1} aria-label="Next image variant" onClick={() => swipeImage(index + 1)}>›</button><a href={'/api/media/' + selected.id} download>Download image</a><button disabled={locked} onClick={() => { setPrompt(selected.prompt); setIllustrate(true); }}>Regenerate image…</button></figcaption>
      <label class="check-label"><input type="checkbox" checked={!!selected.use_in_chat} disabled={locked} onChange={e => void run('select-image', { asset: selected.id, useInChat: e.currentTarget.checked })}/><span>Use this image in chat</span></label>
      <p class="hint">{selected.use_in_chat ? 'Actual image bytes are sent to your chat provider: up to 4 selected images in recent context. A vision-capable model is required.' : 'Display only. This image is not sent with chat.'} {selected.stale && 'This illustration predates a text edit.'} Switching images affects future replies, not earlier messages.</p>
      <details><summary>Image prompt</summary><p class="media-prompt">{selected.prompt}</p></details>
    </figure>}
    {!!mediaState.voices.length && <div class="read-aloud"><label>Read-aloud voice<select aria-label="Read-aloud voice" value={voice} disabled={locked} onChange={e => { const id = e.currentTarget.value; setVoice(id); try { localStorage.setItem('lowriter-voice-' + message.conversation, id); } catch {} }}><option value="">Choose voice…</option>{mediaState.voices.map(v => <option value={v.id}>{v.name}</option>)}</select></label><button disabled={locked || !mediaState.voices.some(v => v.id === voice)} onClick={() => void run('narrate', { voicePreset: voice })}>Read aloud (credits if not cached)</button></div>}
    {!!audio.length && <div class="saved-audio"><label>Saved AI audio<select aria-label="Saved AI audio" value={audioId} onChange={e => setAudioId(e.currentTarget.value)}><option value="">Choose recording…</option>{audio.map(a => <option value={a.id}>{a.label}{a.stale ? ' · older text' : ''} · {new Date(a.created).toLocaleTimeString()}</option>)}</select></label>{audioId && <><audio ref={audioRef} controls preload="none" src={'/api/media/' + audioId}/><a href={'/api/media/' + audioId} download>Download MP3</a></>}<p class="hint">Saved playback is local and does not regenerate audio. Recordings from before a text edit remain available and are marked older text.</p></div>}
    {busy && <p role="status">Working… Use Stop all to cancel. No automatic retries.</p>}{notice && <p role="status">{notice}</p>}{error && <p class="error" role="alert">{error}</p>}
  </section>;
}
